version: '3.7'

services:
  backend:
    container_name: backend
    restart: always
    build: ../FastAPI
    ports:
      - 8001:8000/tcp
    volumes:
      - ../FastAPI:/FastAPI
    networks:
      - bridge

  db:
    container_name: db
    image: postgres:10
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - POSTGRES_DB=gotest
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - bridge

  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    ports:
      - 5051:5050/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - db
    networks:
      - bridge


volumes:
  pgdata:

networks:
  bridge:
    driver: bridge
